services:
  api:
    build: .
    ports:
      - '9999:9999'

    cpus: '0.5'
    mem_limit: '150M'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=rinha
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rinha
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d rinha']
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - '5432:5432'

volumes:
  pg_data:
